#!/usr/bin/env bash

os=$(uname)
PROVIDER="<REPLACE_ME>"
VERSION="v$(go run ${PROVIDER}/version.go)"

if [ "$(command -v goreleaser)" = "" ]; then
  echo "goreleaser is not installed. Please visit https://goreleaser.com/install/ for more information."
  exit 1
fi

echo "Pulling down latest from origin"
git pull origin master

echo "Switching to master branch"
git checkout master

echo "Checking if master branch is clean"
if [ "$(git status --porcelain)" != "" ]; then
  echo "branch is not clean. please add/commit or stage any changes first"
  exit 1
fi

echo "Checking if the tag already exists"
if git show ${VERSION} >> /dev/null 2>&1 || false ; then
  echo "tag ${VERSION} already exists. Did you forget to bump the version in version.go file?"
  exit 1
fi

echo "Checking if .goreleaser.yml is valid"
goreleaser check

echo "Creating new release tag ${VERSION}"
git tag -a "${VERSION}" -m "Release ${VERSION}"

echo "Pushing new release tag ${VERSION} to upstream origin"
git push origin "${VERSION}"