// Copyright 2020
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by gen-accessors; DO NOT EDIT.
package api

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (e *Environment) GetID() string {
	if e == nil || e.ID == nil {
		return ""
	}
	return *e.ID
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (e *Environment) GetName() string {
	if e == nil || e.Name == nil {
		return ""
	}
	return *e.Name
}

// GetProduction returns the Production field if it's non-nil, zero value otherwise.
func (e *Environment) GetProduction() bool {
	if e == nil || e.Production == nil {
		return false
	}
	return *e.Production
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (e *EnvironmentRequest) GetName() string {
	if e == nil || e.Name == nil {
		return ""
	}
	return *e.Name
}

// GetProduction returns the Production field if it's non-nil, zero value otherwise.
func (e *EnvironmentRequest) GetProduction() bool {
	if e == nil || e.Production == nil {
		return false
	}
	return *e.Production
}

// GetLimit returns the Limit field if it's non-nil, zero value otherwise.
func (g *GenericListResult) GetLimit() int {
	if g == nil || g.Limit == nil {
		return 0
	}
	return *g.Limit
}

// GetOffset returns the Offset field if it's non-nil, zero value otherwise.
func (g *GenericListResult) GetOffset() int {
	if g == nil || g.Offset == nil {
		return 0
	}
	return *g.Offset
}

// GetTotalCount returns the TotalCount field if it's non-nil, zero value otherwise.
func (g *GenericListResult) GetTotalCount() int {
	if g == nil || g.TotalCount == nil {
		return 0
	}
	return *g.TotalCount
}

// GetCreationTime returns the CreationTime field if it's non-nil, zero value otherwise.
func (s *Segment) GetCreationTime() int64 {
	if s == nil || s.CreationTime == nil {
		return 0
	}
	return *s.CreationTime
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (s *Segment) GetDescription() string {
	if s == nil || s.Description == nil {
		return ""
	}
	return *s.Description
}

// GetEnvironment returns the Environment field.
func (s *Segment) GetEnvironment() *Environment {
	if s == nil {
		return nil
	}
	return s.Environment
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (s *Segment) GetName() string {
	if s == nil || s.Name == nil {
		return ""
	}
	return *s.Name
}

// HasTags checks if Segment has any Tags.
func (s *Segment) HasTags() bool {
	if s == nil || s.Tags == nil {
		return false
	}
	if len(s.Tags) == 0 {
		return false
	}
	return true
}

// GetTrafficType returns the TrafficType field.
func (s *Segment) GetTrafficType() *TrafficType {
	if s == nil {
		return nil
	}
	return s.TrafficType
}

// HasObjects checks if SegmentListResult has any Objects.
func (s *SegmentListResult) HasObjects() bool {
	if s == nil || s.Objects == nil {
		return false
	}
	if len(s.Objects) == 0 {
		return false
	}
	return true
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (t *Tag) GetName() string {
	if t == nil || t.Name == nil {
		return ""
	}
	return *t.Name
}

// GetDisplayAttributeID returns the DisplayAttributeID field if it's non-nil, zero value otherwise.
func (t *TrafficType) GetDisplayAttributeID() string {
	if t == nil || t.DisplayAttributeID == nil {
		return ""
	}
	return *t.DisplayAttributeID
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (t *TrafficType) GetID() string {
	if t == nil || t.ID == nil {
		return ""
	}
	return *t.ID
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (t *TrafficType) GetName() string {
	if t == nil || t.Name == nil {
		return ""
	}
	return *t.Name
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (t *TrafficType) GetType() string {
	if t == nil || t.Type == nil {
		return ""
	}
	return *t.Type
}

// GetWorkspace returns the Workspace field.
func (t *TrafficType) GetWorkspace() *Workspace {
	if t == nil {
		return nil
	}
	return t.Workspace
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (w *Workspace) GetID() string {
	if w == nil || w.ID == nil {
		return ""
	}
	return *w.ID
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (w *Workspace) GetName() string {
	if w == nil || w.Name == nil {
		return ""
	}
	return *w.Name
}

// GetRequiresTitleAndComments returns the RequiresTitleAndComments field if it's non-nil, zero value otherwise.
func (w *Workspace) GetRequiresTitleAndComments() bool {
	if w == nil || w.RequiresTitleAndComments == nil {
		return false
	}
	return *w.RequiresTitleAndComments
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (w *Workspace) GetType() string {
	if w == nil || w.Type == nil {
		return ""
	}
	return *w.Type
}

// HasObjects checks if Workspaces has any Objects.
func (w *Workspaces) HasObjects() bool {
	if w == nil || w.Objects == nil {
		return false
	}
	if len(w.Objects) == 0 {
		return false
	}
	return true
}
