// Copyright 2020
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by gen-accessors; DO NOT EDIT.
package api

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (e *Environment) GetID() string {
	if e == nil || e.ID == nil {
		return ""
	}
	return *e.ID
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (e *Environment) GetName() string {
	if e == nil || e.Name == nil {
		return ""
	}
	return *e.Name
}

// GetProduction returns the Production field if it's non-nil, zero value otherwise.
func (e *Environment) GetProduction() bool {
	if e == nil || e.Production == nil {
		return false
	}
	return *e.Production
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (e *EnvironmentRequest) GetName() string {
	if e == nil || e.Name == nil {
		return ""
	}
	return *e.Name
}

// GetProduction returns the Production field if it's non-nil, zero value otherwise.
func (e *EnvironmentRequest) GetProduction() bool {
	if e == nil || e.Production == nil {
		return false
	}
	return *e.Production
}
